### ISSUE TITLE
.DS_Store Files Failed the Generate of Test Report

### ISSUE THREAD

**Issue by Lancasterwu** [gkapfham/speed-surprises#17]
`.DS_Store` files are generated in Apple macOS operating system to stores custom attributes of its containing folder. It may make conflicts when we are using Travis CI to generate reports since Travis CI is running within a virtual environment of `Linux`. 
I think this is probably the reason that the master branch was failing after PR https://github.com/gkapfham/speed-surprises/pull/7 was merged.

**Comment by lussierc** [comment]
Hi @Lancasterwu, thank you for notifying me of this issue, I will deal with it either today or sometime over the weekend.

I will use the command below to remove the files.
```
find . -name .DS_Store -print0 | xargs -0 git rm --ignore-unmatch
```

I will then add support for ignoring `.DS_Store` to the `.gitignore` file.

**Comment by lussierc** [comment]
I have merged a fixed pull request into master for the Fibonacci functions. As a result, I am closing this issue.
